extends "res://Classes/Reach.gd"

#IF AT REACH THEN DIRECTLY CHECK FOR HIT - HURTBOX FROM OBJET IS NOT SUPPOSED TO CALL FOR A HIT BUT THE OTHER WAY AROUND. AKA. OBJET AT REACH CHECKING IF I'M HITTING HIT
